### ISSUE TITLE
Put all versions in common file(s) instead of repeating them

### ISSUE THREAD

**Issue by zimmski** [symflower/vmutils-bin#3]
E.g. we have Choco/vmagent/tools/chocolateyinstall.ps1 and Formula/vmagent.rb where we use the same VMAgent version. Having the same version everywhere is usually fine but it is a common place for error when they get out of sync.

This issue should move all versions into either a common "package.json" file and then reuse the versions from there, or into conf/version/${identifier}.version files, and then use those versions in all places. This leads to having all versions/hashes/packaging-meta/... in one place instead of multiple.

**Comment by Munsio** [comment]
My ideal workflow would be a config file for dependabot or renovate. To automatically update the versions inside the files when a new release was tagged by victoria metrics which creates a PR on this repo.

Why:
Chocolatey:
- You specify the version of the package itself inside the XML
- We also should add the sha256 checksum for the package inside the `install` file.
- Service Wrapper version has to be done inside the `install` file.
Brew:
- We need also to generate the sha256 checksum for the `tar.gz` package when updating the version

With one of the pods creating a PR we could use a Github Action to update the versions and additional parts we need in the same PR too. So everything inside this repo is self contained and mostly maintenance free.

**Comment by zimmski** [comment]
Fine with me, but we do not need that for our internal work at the moment. Should be an outside contribution.
