### ISSUE TITLE
Automatic tags and releases

### ISSUE THREAD

**Issue by zimmski** [symflower/vmutils-bin#6]
With https://github.com/symflower/vmutils-bin/pull/5 we are automatically updating the version of VictoriaMetrics. However, this repository does not have tags nor releases yet. The reason is that we do not want to maintain them manually but we want them maintainted automatically so we can invest the time of our life into something else.

**Comment by MTSym** [comment]
With automatic tags and releases we should also provide the chocolatey nuspec package as asset as the moderation of chocolatey is so slow.
